services:
  app:
    build: .
    image: googlecalintegration
    # command: python manage.py makemigrations
    # command: python manage.py migrate
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000